name: 🚀 Feature Request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What would you like to see?
      placeholder: "Describe the feature or enhancement..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Why is this useful?
      placeholder: "Tell us what problem it solves or improves..."
